In [1]:
import numpy as np

In [4]:
a = np.array([1,4,3])
b = np.array([[1,3,4],[6,4,7]],dtype=float)

In [5]:
a

array([1, 4, 3])

In [6]:
b


array([[1., 3., 4.],
       [6., 4., 7.]])

In [8]:
s=np.arange(4,20,2)
s

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr=np.linspace(2,4)
arr

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [16]:
arr=np.random.randint(20,49,5)
arr

array([35, 28, 47, 32, 38])

salam

In [27]:
b.shape

(2, 3)

In [55]:
len(a)

3

In [19]:
b.ndim

2

In [20]:
a.ndim

1

In [21]:
a.size

3

In [22]:
b.size

6

In [24]:
a.dtype.name

'int32'

In [26]:
a.astype(int)

array([1, 4, 3])

In [57]:
np.insert(a,1,5)

array([1, 5, 4, 3])

In [29]:
np.delete(b,1)

array([1., 4., 6., 4., 7.])

In [30]:
b

array([[1., 3., 4.],
       [6., 4., 7.]])

In [35]:
np.delete(b,1,1)

array([[1., 4.],
       [6., 7.]])

In [33]:
b.reshape(3,2)

array([[1., 3.],
       [4., 6.],
       [4., 7.]])

In [34]:
b

array([[1., 3., 4.],
       [6., 4., 7.]])

In [36]:
b

array([[1., 3., 4.],
       [6., 4., 7.]])

In [37]:
np.delete(b,1,1)

array([[1., 4.],
       [6., 7.]])

In [38]:
np.delete(b,1,0)

array([[1., 3., 4.]])

In [39]:
np.append(a,b)

array([1., 4., 3., 1., 3., 4., 6., 4., 7.])

In [40]:
a[1]

4

In [42]:
b[0,2]

4.0

In [43]:
a[a<2]

array([1])

In [44]:
a+b

array([[ 2.,  7.,  7.],
       [ 7.,  8., 10.]])

In [45]:
np.add(a,b)

array([[ 2.,  7.,  7.],
       [ 7.,  8., 10.]])

In [48]:
np.subtract(b,a)

array([[ 0., -1.,  1.],
       [ 5.,  0.,  4.]])

In [49]:
np.multiply(a,b)

array([[ 1., 12., 12.],
       [ 6., 16., 21.]])

In [50]:
np.sqrt(a)

array([1.        , 2.        , 1.73205081])

In [51]:
b.mean()

4.166666666666667

In [52]:
np.max(a)

4

In [53]:
a.max()

4

In [54]:
a.std()

1.247219128924647